sample_payload: 'sample_payload.json'
EXPT_DIR : "log"
DATA_DIR : "data"
WEIGHTS_DIR : "weights"
exp_name: "reuters-text-classification"

### TRAIN FUNCTION ARGS ###
trainsize: 4659
model: "roberta-base" 
# Choose from 
# albert-base-v2
# albert-large-v2
# distilbert-base-cased
# xlm-roberta-base
# roberta-base
# bert-base-cased
# bert-base-uncased
# xlnet-base-cased
# for more choices visit: https://huggingface.co/models
dataset: "Reuters"
learning_rate: 0.00002
warmup_steps: 200
max_steps: 600
logging_steps: 1000
max_seq_length: 256
seed: -1 # If -1, we make it random
