sample_payload: 'sample_payload.json'
EXPT_DIR : "./log"
DATA_DIR : "./data"
WEIGHTS_DIR : "./weights"
exp_name: "urban-sound"

### TRAIN FUNCTION ARGS ###
train_epochs: 50
batch_size: 64
train_size: 7888
test_size: 837
learning_rate: 1e-4
momentum: 0.9
split_train: 0.80